import { useEffect } from 'react';

const TECH_STACK = [
  { cat: '🌸 Frontend', items: ['React.js', 'React Router DOM', 'React Simple Maps', 'Recharts', 'CSS3'] },
  { cat: '🌿 Backend', items: ['Node.js', 'Express.js', 'MongoDB', 'Mongoose', 'NodeCache'] },
  { cat: '🌺 APIs', items: ['GNews API', 'OpenWeatherMap', 'REST Countries', 'ExchangeRate API', 'Anthropic Claude'] },
  { cat: '🌼 Tools', items: ['Axios', 'dotenv', 'Nodemon', 'Git'] },
];

const FEATURES = [
  { icon: '🗺', title: 'Interactive World Map', desc: 'Click any country to explore with hover highlights, tooltips, zoom and pan.' },
  { icon: '📰', title: 'Live News Feed', desc: 'Real-time news headlines via GNews API for any country.' },
  { icon: '🌤', title: 'Live Weather', desc: 'Current conditions for each country capital via OpenWeatherMap.' },
  { icon: '💱', title: 'Currency Exchange', desc: 'Live rates powered by ExchangeRate API.' },
  { icon: '📊', title: 'Market Data', desc: 'Major stock indices, currencies, and commodities in real time.' },
  { icon: '✦', title: 'AI Summaries', desc: 'Country intelligence briefs generated by Claude AI.' },
];

export default function AboutPage() {
  useEffect(() => { document.title = 'About — News Atlas'; }, []);

  return (
    <main className="main-content page-wrapper">
      <div className="petal-bg" />

      <div style={{
        background: 'linear-gradient(135deg, var(--blush) 0%, var(--parchment) 60%, rgba(122,158,126,0.1) 100%)',
        borderBottom: '1px solid var(--border)',
        padding: '5rem 2rem 4rem',
        textAlign: 'center',
        position: 'relative',
        overflow: 'hidden'
      }}>
        <div style={{ position: 'absolute', top: -20, left: '5%', fontSize: '6rem', opacity: 0.05, pointerEvents: 'none' }}>🌷</div>
        <div style={{ position: 'absolute', bottom: -10, right: '5%', fontSize: '7rem', opacity: 0.05, pointerEvents: 'none' }}>💐</div>
        <div className="section-eyebrow">Our Story</div>
        <h1 className="hero-title" style={{ fontSize: 'clamp(2.5rem, 5vw, 4rem)', marginBottom: '1rem' }}>
          Built for <em>Curious Minds</em>
        </h1>
        <div className="hero-divider">❀ ✿ ❀</div>
        <p style={{ color: 'var(--ink-muted)', font: '300 1rem var(--font-body)', fontStyle: 'italic', maxWidth: 520, margin: '1.25rem auto 0', lineHeight: 1.9 }}>
          News Atlas connects the world's data — news, weather, markets, and AI insights — to any country, beautifully and instantly.
        </p>
      </div>

      <div className="container" style={{ padding: '3rem 1.5rem' }}>
        {/* Mission */}
        <div className="card" style={{ textAlign: 'center', padding: '3rem', marginBottom: '3rem' }}>
          <div style={{ fontSize: '3rem', marginBottom: '1rem' }}>🌍</div>
          <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '1.8rem', fontStyle: 'italic', marginBottom: '1rem' }}>Our Mission</h2>
          <p style={{ color: 'var(--ink-muted)', maxWidth: '600px', margin: '0 auto', lineHeight: 1.9, fontWeight: 300 }}>
            To make global information accessible and beautiful. In an age of information overload,
            News Atlas provides a clean, elegant interface to understand what's happening in any
            corner of the world — with data you can trust.
          </p>
        </div>

        {/* Features */}
        <div className="section-eyebrow">What We Offer</div>
        <h2 className="section-title">Features</h2>
        <div className="grid-3" style={{ marginBottom: '3rem' }}>
          {FEATURES.map(f => (
            <div key={f.title} className="card">
              <div style={{ fontSize: '2rem', marginBottom: '0.75rem' }}>{f.icon}</div>
              <div style={{ fontFamily: 'var(--font-display)', fontWeight: 600, fontSize: '1.05rem', fontStyle: 'italic', marginBottom: '0.4rem' }}>{f.title}</div>
              <div style={{ fontSize: '0.85rem', color: 'var(--ink-muted)', lineHeight: 1.7, fontWeight: 300 }}>{f.desc}</div>
            </div>
          ))}
        </div>

        <div className="ornament">❀ ✿ ❀ ✿ ❀</div>

        {/* Tech Stack */}
        <div className="section-eyebrow" style={{ marginTop: '2rem' }}>Under the Hood</div>
        <h2 className="section-title">Technology Stack</h2>
        <div className="grid-2" style={{ marginBottom: '3rem' }}>
          {TECH_STACK.map(t => (
            <div key={t.cat} className="card">
              <div style={{ fontFamily: 'var(--font-display)', fontStyle: 'italic', fontSize: '1rem', color: 'var(--rose)', marginBottom: '0.75rem' }}>{t.cat}</div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem' }}>
                {t.items.map(item => (
                  <span key={item} style={{ background: 'var(--parchment)', border: '1px solid var(--border)', borderRadius: '20px', padding: '0.25rem 0.75rem', fontSize: '0.8rem' }}>
                    {item}
                  </span>
                ))}
              </div>
            </div>
          ))}
        </div>

        {/* Developer */}
        <div className="card" style={{ textAlign: 'center', padding: '3rem', marginBottom: '2rem' }}>
          <div style={{ width: 80, height: 80, borderRadius: '50%', background: 'linear-gradient(135deg, var(--rose-light), var(--gold))', margin: '0 auto 1.25rem', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '2rem' }}>
            👨‍💻
          </div>
          <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '1.6rem', fontStyle: 'italic', marginBottom: '0.5rem' }}>Crafted with Care</h2>
          <p style={{ color: 'var(--ink-muted)', marginBottom: '1.5rem', fontWeight: 300, maxWidth: 400, margin: '0 auto 1.5rem' }}>
            News Atlas is built with attention to every detail — clean architecture, real API integrations, and production-grade patterns.
          </p>
          <div style={{ display: 'flex', gap: '1rem', justifyContent: 'center', flexWrap: 'wrap' }}>
            <a href="https://github.com" target="_blank" rel="noopener noreferrer" className="btn btn-ghost">⭐ GitHub</a>
            <a href="/contact" className="btn btn-primary">📩 Contact 🌸</a>
          </div>
        </div>
      </div>
    </main>
  );
}
