import { useEffect } from 'react';

const TECH = [
  { cat: 'Frontend', items: ['React.js', 'React Router', 'React Simple Maps', 'Recharts', 'CSS3'] },
  { cat: 'Backend', items: ['Node.js', 'Express.js', 'MongoDB', 'Mongoose', 'NodeCache'] },
  { cat: 'APIs', items: ['GNews', 'OpenWeatherMap', 'REST Countries', 'ExchangeRate', 'Anthropic Claude'] },
  { cat: 'Tools', items: ['Axios', 'dotenv', 'Firebase Auth', 'Git'] },
];

const FEATURES = [
  { icon: '🗺', title: 'Interactive World Map', desc: 'Click any country to explore. Hover highlights, tooltips, zoom and pan.' },
  { icon: '📰', title: 'Live News Feed', desc: 'Real-time headlines via GNews API for any country.' },
  { icon: '🌤', title: 'Weather', desc: 'Current conditions for each country capital.' },
  { icon: '💱', title: 'Currency Rates', desc: 'Live exchange rates for every country currency.' },
  { icon: '📊', title: 'Market Data', desc: 'Stock indices, currencies, and commodities.' },
  { icon: '✦', title: 'AI Summaries', desc: 'Country intelligence briefs generated by Claude AI.' },
];

export default function AboutPage() {
  useEffect(() => { document.title = 'About — News Atlas'; }, []);

  return (
    <main className="main-content page-wrapper">

      <div style={{ background: 'var(--surface)', borderBottom: '1px solid var(--border)', padding: '40px 20px 32px' }}>
        <div className="container" style={{ padding: 0 }}>
          <p className="section-eyebrow">Our story</p>
          <h1 className="section-title" style={{ fontSize: '2rem', marginBottom: '8px' }}>About News Atlas</h1>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.95rem', maxWidth: 520, lineHeight: 1.7 }}>
            News Atlas makes global information accessible. Click a country on the map and instantly see its news, weather, currency, and market data — all in one place.
          </p>
        </div>
      </div>

      <div className="container" style={{ padding: '40px 20px' }}>

        <h2 className="section-title" style={{ marginBottom: '16px' }}>Features</h2>
        <div className="grid-3" style={{ marginBottom: '48px' }}>
          {FEATURES.map(f => (
            <div key={f.title} className="card">
              <div style={{ fontSize: '1.6rem', marginBottom: '10px' }}>{f.icon}</div>
              <div style={{ fontWeight: 600, marginBottom: '5px', fontSize: '0.95rem' }}>{f.title}</div>
              <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)', lineHeight: 1.6 }}>{f.desc}</div>
            </div>
          ))}
        </div>

        <h2 className="section-title" style={{ marginBottom: '16px' }}>Technology</h2>
        <div className="grid-2" style={{ marginBottom: '48px' }}>
          {TECH.map(t => (
            <div key={t.cat} className="card">
              <div style={{ fontWeight: 600, fontSize: '0.85rem', color: 'var(--accent)', marginBottom: '12px', textTransform: 'uppercase', letterSpacing: '0.06em', fontFamily: 'var(--font-mono)' }}>
                {t.cat}
              </div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px' }}>
                {t.items.map(item => (
                  <span key={item} style={{ background: 'var(--surface2)', border: '1px solid var(--border)', borderRadius: '4px', padding: '3px 10px', fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                    {item}
                  </span>
                ))}
              </div>
            </div>
          ))}
        </div>

        <div className="card" style={{ textAlign: 'center', padding: '32px' }}>
          <h2 style={{ fontFamily: 'var(--font-head)', fontSize: '1.3rem', marginBottom: '8px' }}>Get in Touch</h2>
          <p style={{ color: 'var(--text-muted)', marginBottom: '20px', fontSize: '0.9rem' }}>Have feedback or ideas? We'd love to hear from you.</p>
          <a href="/contact" className="btn btn-primary">Contact Us →</a>
        </div>

      </div>
    </main>
  );
}
