import { useEffect } from 'react';

const TECH_STACK = [
  { cat: 'Frontend', items: ['React.js', 'React Router DOM', 'React Simple Maps', 'Recharts', 'CSS3'] },
  { cat: 'Backend', items: ['Node.js', 'Express.js', 'MongoDB', 'Mongoose', 'NodeCache'] },
  { cat: 'APIs', items: ['GNews API', 'OpenWeatherMap', 'REST Countries', 'ExchangeRate API', 'Anthropic Claude'] },
  { cat: 'Tools', items: ['Axios', 'dotenv', 'Nodemon', 'Git'] },
];

const FEATURES = [
  { icon: '🗺', title: 'Interactive World Map', desc: 'Click any country to explore — with hover highlights, tooltips, zoom and pan.' },
  { icon: '📰', title: 'Live News', desc: 'Real-time news headlines from trusted global sources via GNews API.' },
  { icon: '🌤', title: 'Live Weather', desc: 'Current temperature, humidity, and conditions for each country capital.' },
  { icon: '💱', title: 'Currency Exchange', desc: 'Live exchange rates and currency comparison powered by ExchangeRate API.' },
  { icon: '📊', title: 'Market Data', desc: 'Major stock indices, currencies, and commodity prices in real time.' },
  { icon: '✦', title: 'AI Summaries', desc: 'Country intelligence briefs generated by Claude AI for context and insight.' },
];

export default function AboutPage() {
  useEffect(() => {
    document.title = 'About — News Atlas';
  }, []);

  return (
    <main className="main-content page-wrapper">
      <div className="hero" style={{ paddingBottom: '2rem' }}>
        <div className="hero-eyebrow">// ABOUT THIS PROJECT</div>
        <h1 className="hero-title">
          Built for <span className="accent">Curious Minds</span>
        </h1>
        <p className="hero-subtitle">
          News Atlas is a real-time intelligence platform that connects the world's
          data — news, weather, markets, and AI insights — to any country, instantly.
        </p>
      </div>

      <div className="container">
        {/* Mission */}
        <div className="card" style={{ marginBottom: '2rem', textAlign: 'center', padding: '2.5rem' }}>
          <div style={{ fontSize: '3rem', marginBottom: '1rem' }}>🌍</div>
          <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '1.5rem', marginBottom: '1rem' }}>Our Mission</h2>
          <p style={{ color: 'var(--text-muted)', maxWidth: '600px', margin: '0 auto', lineHeight: 1.8 }}>
            To make global information accessible and beautiful. In an age of information
            overload, News Atlas provides a clean, elegant interface to understand what's
            happening in any corner of the world — with data you can trust.
          </p>
        </div>

        {/* Features */}
        <h2 className="section-title">Features</h2>
        <div className="grid-3" style={{ marginBottom: '3rem' }}>
          {FEATURES.map(f => (
            <div key={f.title} className="card">
              <div style={{ fontSize: '2rem', marginBottom: '0.75rem' }}>{f.icon}</div>
              <div style={{ fontWeight: 700, marginBottom: '0.4rem' }}>{f.title}</div>
              <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)', lineHeight: 1.6 }}>{f.desc}</div>
            </div>
          ))}
        </div>

        {/* Tech stack */}
        <h2 className="section-title">Technology Stack</h2>
        <div className="grid-2" style={{ marginBottom: '3rem' }}>
          {TECH_STACK.map(t => (
            <div key={t.cat} className="card">
              <div style={{ fontSize: '0.7rem', fontFamily: 'var(--font-mono)', color: 'var(--accent)', textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: '0.75rem' }}>
                {t.cat}
              </div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem' }}>
                {t.items.map(item => (
                  <span key={item} style={{
                    background: 'var(--surface2)',
                    border: '1px solid var(--border)',
                    borderRadius: '6px',
                    padding: '0.25rem 0.65rem',
                    fontSize: '0.8rem',
                    fontFamily: 'var(--font-mono)'
                  }}>
                    {item}
                  </span>
                ))}
              </div>
            </div>
          ))}
        </div>

        {/* Developer info */}
        <div className="card" style={{ marginBottom: '3rem', textAlign: 'center', padding: '2.5rem' }}>
          <div style={{ width: 80, height: 80, borderRadius: '50%', background: 'linear-gradient(135deg, var(--accent), var(--accent3))', margin: '0 auto 1.25rem', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '2rem' }}>
            👨‍💻
          </div>
          <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '1.4rem', marginBottom: '0.25rem' }}>Developed with Craft</h2>
          <p style={{ color: 'var(--text-muted)', marginBottom: '1.25rem', fontSize: '0.9rem' }}>
            News Atlas is built with attention to detail — clean code architecture,
            real API integrations, and production-grade patterns.
          </p>
          <div style={{ display: 'flex', gap: '1rem', justifyContent: 'center', flexWrap: 'wrap' }}>
            <a href="https://github.com" target="_blank" rel="noopener noreferrer" className="btn btn-ghost">⭐ GitHub</a>
            <a href="/contact" className="btn btn-primary">📩 Contact</a>
          </div>
        </div>
      </div>
    </main>
  );
}
